### ISSUE TITLE
Порядок смены целей

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#29]
Необходимо прояснение, как сейчас работает механизм смены целей. 

- в приложении можно менять их в любое время
- в онбординге написано, что цели выбираются "на несколько дней"
- в ТЗ написано "Цели выбираются и приоритизируются на 3 дня. Через 3 дня пользователю будет предложено задать цели на месяц"

@danwhale @kapc3d  как сейчас реализовано? 

@davidvirabian на контроль

**Comment by kapc3d** [comment]
сейчас у нас кнопка активна постоянно, чтобы был механизм ограничения по времени нам надо с бека получать мету о том можно менять цели или нет при открытии прогресса. тогда мы сделаем блокировку на кнопку смены целей

**Comment by danwhale** [comment]
Да, откладывали эту задачу на конец, как самую боль, в т.ч. недетализированную: 

- Как мы делаем? скрываем кнопку? пересылаем уведомление с напоминанием зайти в меню, активировав кнопку или же просто блокируем юзеру весь экран в приложении чтобы он насильно проставил?

**Comment by kapc3d** [comment]
мое предлоежние:
- функция должна работать с локом на время, а не с периодичностью. типа не "поменять можешь только в поледнюю среду каждого месяца", а "поменять можешь не чаще чем раз в месяц", то есть пока цели не сменил у него опция смены доступна, как только сменил - лочится на 30 дней например
- при входе в профиль вы нам вместе с статой по целям даете инфу values_changable = true/false и values_change_date = timestamp мы по этой инфе делаем кнопку активной или неактивной при попытке нажать на которую сообщаем пользователю "цели можно поменять тогда то"
- когда функция разлочивается то присылаем нотификейшн "ты можешь сменить приоритеты в целях" с редиректом на окно прогресса (не окно смены целей)

**Comment by kbochenina** [comment]
А у меня предложение (продуктовое) на момент релиза не лочить эту функцию потому что у нас на ней завязана динамика персональных рекомендаций аватара (учитываются цели) + какие ему мотиваторы по целям показываются в Моих делах. Если мы залочим, не будет этой динамики

**Comment by danwhale** [comment]
Согласен

**Comment by kbochenina** [comment]
В итоге оставляем возможность менять цели все время и правим онбординг?

**Comment by danwhale** [comment]
Предлагаю, так, да. Посмотрим потом меняют ли вообще они цели себе ;)

**Comment by danwhale** [comment]
Можно будет сделать уведомление потом с напоминанием

**Comment by kbochenina** [comment]
Закрыто. Онбординг правлю я. Я параллельно модифицирую документ вычитка, дам знать когда соберем все правки по текстам туда.
