### ISSUE TITLE
 С6 - Создание пользовательского события

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#30]
В онбординге указано что ручное событие размечается по целям и тэгам.

Соответствие по целям необходимо, чтобы твой Аватар лучше оценивал твой прогресс, а теги повлияют на качество рекомендаций

В ТЗ тоже:

Созданное событие должно включать в себя следующие данные: название, описание, дату и время начала/окончания события, **разметку по целям и поисковую строку для поиска тегов**; Комментарий: дата и время начала/окончания события изначально задаются такими же, как и у пользователя в момент создания мероприятия. Должно быть визуально отображено то, что пользователь должен добавить минимум 3 тега. Строка поиска тегов, название и поле описания события должны быть пустыми.

Сейчас нету целей и тэгов при добавлении события. 

_Предложение_: не вводить поля целей и тэгов при ручном событии и подправить онбординг, лично я считаю что это будет лучше тк пользователю меньше телодвижений делать чтобы добавить себе событий. А опрашивать про разметку по целям и тэгам - есть спец. уведомление. По целям событие также можно размечать при нажатии на лайк в календаре. @kapc3d @danwhale  принимается ли предложение либо ваши предложения?

Nice 2 have - добавить также в разметку по лайку тэги? Тогда вы можете и самостоятельно разметить событие, и по запросу от аватара.

@davidvirabian  я прошу тебя когда будет достигнуто решение по вопросу, модифицировать карточки фич, внося туда актуальную информацию по решению. ТЗ не будем пока править.

**Comment by danwhale** [comment]
Мы с Андреем так и решили в чате, вроде вопрос тоже поднимался, ещё один аргумент ЗА принятия такого предложения: по истечению события аватар все равно предложит его разметить

**Comment by kbochenina** [comment]
Решение принято. @davidvirabian онбординг (в документе Вычитка) исправлю сама. С тебя по закрытым issues переносить актуальную информацию в карточку фичи. Nice 2 have можно тоже.
