### ISSUE TITLE
O2 - "не работает логин?"

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#31]
@kapc3d 

(1) Заменить текст на:

Попробуйте выполнить следующие шаги:

1. Открыть ИСУ -> "Настройки".
2. Активировать, возможно, повторно, настройку "Использовать пароль ИСУ в ЦДО? (даже если настройка стоит в положении "Да", нужно её сначала установить в "Нет", а затем снова в "Да").
3. Если проблема сохраняется, обратитесь по адресу avatar@itmo.ru, указав ИСУ ID.

(2) Причесать форматирование, Сейчас все в строку, неаккуратно смотрится

**Comment by kapc3d** [comment]
починено, будет в следующей сборке
