### ISSUE TITLE
Доступ аватара к данным - продуктовый вопрос [feature-candidate]

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#34]
@danwhale @kapc3d @davidvirabian 

Простановка галок в Приватность - Доступ аватара к данным ничего не меняет в приложении. Я понимаю что логика такая что он это не использует положим при рекомендациях.. но даже если снимешь галку например с e-mail, в разделе Мои данные это поле все равно не исчезает (= считай доступно Аватару).

Вариант 1: связать снятие галки в Доступ аватара к данным и наличие / отсутствие поля в разделе Мои данные (желательный)

Вариант 2: ничего не делать записать в nice2have

**Comment by danwhale** [comment]
Фича в целом маленькая требует правок по бэку и фронту, я бы отложил в список кандидатов, чтобы мы выдохнули  приоретизировали, в целом, тикет может тут висеть, можно проработать префиксы и лейблы тикетам (чтобы отражать статус\сортировать)

**Comment by kbochenina** [comment]
Я не могу ставить метки и кого то назначать добавила в названии

**Comment by kapc3d** [comment]
сделаем по первому варианту
