### ISSUE TITLE
Онбординг - проверка функциональности

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#38]
Не могу проверить механику онбординга от начала до конца при первом входе

Раньше была проблема например что некоторые экраны показываются многократно. А логика вроде что каждый экран 1 раз показывается.

**Comment by danwhale** [comment]
@kbochenina проверку онбординга нужно делать по запросу. Можешь писать мне в тг и я буду сбрасывать настройки.

**Comment by kbochenina** [comment]
По механике вроде нормально, закрываю
