### ISSUE TITLE
Переключение типов событий - цветовая дифференциация - уточнение

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#40]
Нужно пояснение (возможно обсуждалось)

У меня ручное событие с синей полосочкой в разделе "Все", а раздел "Мои события" - оранжевый. Я думала что полосочки в разделе все соответствуют цветам разделов и маркируют различные типы добавления событий. Или что означает маркировка полоской в разделе "Все"?

![изображение](https://user-images.githubusercontent.com/5405987/108235256-b30c8380-7156-11eb-9b94-5860d92cb60a.png)

![изображение](https://user-images.githubusercontent.com/5405987/108235275-b9026480-7156-11eb-9c3d-9cfb01276fc9.png)

**Comment by kapc3d** [comment]
добавлено явное цветовое обозначение даже на кнопках, ждем обновления бэка чтобы это работало

**Comment by danwhale** [comment]
летит в деплой. 

@kapc3d я ток посмотрел там именно когда подкрашивается текст кнопок, красный и оранжевый сложно дифференцируемы, мб ещё обводку сделать?

**Comment by kbochenina** [comment]
Полоски соответствуют цветам разделов, закрываю
