### ISSUE TITLE
Профиль - индикатор на названии раздела 

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#42]
На названии раздела профиль есть красный индикатор с числом. 

Я думала что там отображается число - инкремент по баллам прогресса, и оно обновляется после совершения новых действий в приложении.

Но после входа в новый билд получила такую картину, которая разбила мою теорию.  

Скриншот 1 - сразу после входа (возможно накопилось 18 новых баллов, думаю я?)

![изображение](https://user-images.githubusercontent.com/5405987/108237779-49da3f80-7159-11eb-8b31-f181f6cfd0f2.png)

Скриншот 2 - переключилась по другим разделам и вернулась (нет, осталось 10, а что такое было 18 - неясно)

![изображение](https://user-images.githubusercontent.com/5405987/108237954-7beba180-7159-11eb-8be2-b9ed333ace7b.png)

Нужно уточнение - как это все-таки реализовано и ок ли продемонстрированная логика?

**Comment by danwhale** [comment]
@kapc3d Андрей, там Ника что-то мутила. Насколько я понимаю, это фронт отлавливает инкримент по целям ДО ВХОДА В ПРОФИЛЬ. То есть вход в профиль обнуляет индикатор.

**Comment by kbochenina** [comment]
@danwhale @kapc3d еще кейс - дробные инкременты (см. скриншот)

![изображение](https://user-images.githubusercontent.com/5405987/108240978-67f56f00-715c-11eb-8ae2-401b2b3f0fa5.png)

**Comment by davidvirabian** [comment]
"Я думала что там отображается число - инкремент по баллам прогресса, и оно обновляется после совершения новых действий в приложении."  так было и должно быть. Видимо, баг.

**Comment by kapc3d** [comment]
про дробные числа:
@danwhale мы же договаривались, что вы будете у себя округлять балы при выдаче нам? здесь видать "защиту от бэка" не включили на округление...

**Comment by danwhale** [comment]
@hainamantik Саш, а у нас где-то остались дробные?(

**Comment by hainamantik** [comment]
> @hainamantik Саш, а у нас где-то остались дробные?(

Нет, приросты +0.3 увеличил до +1.
Вообще этот функционал (по отображению плюсбаллов над профилем) с нами не согласован, и фронтами для этого используется апи, которое вообще не предназначено для реалтайм отображения прогресса. В данный момент на каждое действие юзера (например, нажатие лайка) вы запрашиваете у нас полную сводку по прогрессу с 2014 года, чем можете неплохо ударить по производительности бэка.

По тз договаривались показывать приросты только на онбординге и только один раз, но почему-то это проигнорили.
Хотите реалтайм апдейты - надо строить взаимодействия на вебсокетах

**Comment by Monteguen** [comment]
можно вызывать progress только если фокус на профиле, а в бадже не указывать числа, кроме онбординга
можно указывать в бадже суммированные инкременты, которые указаны по тз (+1 на лайк дизлайк, +3 на событие), но в таком случае возникают несоответствия (по баджу кажется что +5, но при вызову progress инкремент другой)

**Comment by kapc3d** [comment]
> > @hainamantik Саш, а у нас где-то остались дробные?(
> 
> Нет, приросты +0.3 увеличил до +1.
> Вообще этот функционал (по отображению плюсбаллов над профилем) с нами не согласован, и фронтами для этого используется апи, которое вообще не предназначено для реалтайм отображения прогресса. В данный момент на каждое действие юзера (например, нажатие лайка) вы запрашиваете у нас полную сводку по прогрессу с 2014 года, чем можете неплохо ударить по производительности бэка.
> 
> По тз договаривались показывать приросты только на онбординге и только один раз, но почему-то это проигнорили.
> Хотите реалтайм апдейты - надо строить взаимодействия на вебсокетах

с текущими механизмами онбординга во время онбординга (полноэкранный при открытии раздела, а не сценарный) нет возможности адекватно показать эту динамику, однако со стороны @davidvirabian были частые просьбы что надо бы эту динамику показывать. сейчас решение вот такое. соглашусь с тем что фича пущена в разработку без проектирования и в торопях

**Comment by danwhale** [comment]
C @davidvirabian мы обсуждали такую механику, что фронт просто "рисует" без привязки к реальным очкам один раз (в период онбординга) красивые плюсики просто по определённм в ТЗ событиям и всё.

**Comment by davidvirabian** [comment]
> C @davidvirabian мы обсуждали такую механику, что фронт просто "рисует" без привязки к реальным очкам один раз (в период онбординга) красивые плюсики просто по определённым в ТЗ событиям и всё.

Да, так проще гораздо будет.

Можем реализовать? @kapc3d

**Comment by kapc3d** [comment]
@Monteguen понятен механизм рисования бейджей?

**Comment by hainamantik** [comment]
Все дробные числа в рейтингах на бэке убрали

**Comment by kapc3d** [comment]
посмотрите в следующей сборке поведение этого кругляша, вообще оставлять это или нет

**Comment by davidvirabian** [comment]
Задача кругляша - уведомлять юзера о начислении баллов.
Это последнее "живое", что осталось в приложении. Я бы просто в этот кругляш добавил бы ещё знак "+"
(+ балл)
Тогда и логика сходиться будет и проблемы уйдут.
@kbochenina @kapc3d что скажете?

**Comment by kbochenina** [comment]
Да, можно плюсик.

Красный цвет у меня еще путается с красной шкалой (баллы аватара), хотя по идее плюсуется и за баллы аватара и за баллы по целям.

Еще, я не могу понять как это сейчас работает. Я думала так:
- если ты сделал событие, за которое начисляется балл, то этот индикатор загорается
- переходишь в профиль - убирается

Но я вот сейчас попробовала добавить интересы и поставить лайк выдаче - ничего не появляется. Хотя при первом заходе в приложение кругляш был, и убрался при переходе в профиль. На dev

@kapc3d можешь уточнить как сейчас реализовано?

**Comment by kapc3d** [comment]
плюсики починили. появляются при действиях пользователя, пропадают при открытии профиля 
будет в следующей версии - 1.0.3

**Comment by kbochenina** [comment]
Проверила, работает

1.0.3 - rc
