### ISSUE TITLE
Удаление созданного события [в релиз], С8 - Редактирование созданного события [в minor-fix]

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#43]
Висит фича С8 редактирование ручного события

Не нашла в календаре как это сделать - эта есть возможность?

**Comment by kapc3d** [comment]
с нашей стороны упустили, возьмем в работу
@danwhale на вашей стороне ручка не редактирование есть?

**Comment by danwhale** [comment]
Роута такого нет сейчас. На удаление с календаря собственного события вроде тоже =\

**Comment by danwhale** [comment]
Мы тоже появление этой фичи как-то упустили на фоне остального

**Comment by kapc3d** [comment]
> Роута такого нет сейчас. На удаление с календаря собственного события вроде тоже =\

сделайте хотя бы на удаление, редактирование отложим я так понимаю на минорный фикс после релиза

**Comment by danwhale** [comment]
@shpaker тут призываю тебя)

**Comment by kbochenina** [comment]
Удаление надо сделать, да, переназову тикет

**Comment by hainamantik** [comment]
В релиз 22 февраля не входит?

**Comment by kbochenina** [comment]
@hainamantik договаривались, что удаление созданного события в календаре будет (редактирования - не будет)

**Comment by kbochenina** [comment]
Событие удаляется, закрываю
