### ISSUE TITLE
Оценка события из календаря - не сохраняется + вопрос по числу целей

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#44]
(1) Когда в календаре нажимаешь на лайк и размечаешь событие (полезность, число часов и тд), нажимаешь Готово, а потом снова заходишь в лайк на этом событии, то внесенные изменения не сохраняются. То есть у пользователя чувство что аватар не запомнил то что он ввел (ну и ты можешь бесконечное число раз оценивать одно и то же событие)

(2) Написано "Выберите минимум три цели" - но работает (нажимается Готово) и с 1 целью тоже. 

Предложение заменить текст на "Выберите минимум 1 цель". С точки зрения логики, событие не обязательно относится к нескольким целям.

**Comment by danwhale** [comment]
Мы подразумевали, что можно "переоценивать событие" из меню, в целом нужно чёткое требование по механике оценки из календаря.

**Comment by kapc3d** [comment]
мне видится нелогичным с точки зрения пользовательского опыта при повторном открытии опять выдавать форму с заполненными данными. я бы предложил механизм
- при нажатии на палец мы делаем запрос на сервер
- он нам говорит что
> а) пользователь не оценивал и мы даем пользователю оценить
> б) пользователь уже оценивал => мы спрашиваем "Вы уже оценили это событие! Действительно хотите изменить свою оценку? Да/Нет" и на Да выдавать форму переоценки, на Нет возвращать в календарь.

@kbochenina @davidvirabian

**Comment by kapc3d** [comment]
ну либо при получении списка событий метить его как evaluated = true|false

**Comment by danwhale** [comment]
От события идти будет гораздо сложнее, тк принципиально другой компоенент, в целом согласен с этой логикой: 
> а) пользователь не оценивал и мы даем пользователю оценить
> б) пользователь уже оценивал => мы спрашиваем "Вы уже оценили это событие! Действительно хотите изменить свою оценку? Да/Нет" и на Да выдавать форму переоценки, на Нет возвращать в календарь.

@hainamantik Это со стороны бэка требует доп ручку?

**Comment by danwhale** [comment]
При оценке событий лучше нарисовать на фронте Полезность не 0-0.5-1 а 0-50-100.

**Comment by kbochenina** [comment]
В целом да, мне нравится вариант 1 без возможности переоценки. Тк повторная
оценка без ограничения по числу оцениваний - прямая дорога к накрутке
баллов прогресса

чт, 18 февр. 2021 г., 11:39 Andrey <notifications@github.com>:

**Comment by hainamantik** [comment]
Можем создать ручку на проверку того, оценили ассет, или ещё нет. Ручка с историей оценок есть, но она в эту концепцию не укладывается.
Жду вердикта и могу её сделать, если все согласны на невозможность переоценки

**Comment by danwhale** [comment]
@avatar-project/managers-team ждём решения =)

**Comment by davidvirabian** [comment]
Давайте уберем возможность переоценки в данном релизе. 
Не вижу негативных последствий.

**Comment by danwhale** [comment]
@hainamantik -- Саш, бери в работу)

**Comment by hainamantik** [comment]
Ручка добавлена, можно реализовывать на фронте

**Comment by kapc3d** [comment]
взято в работу

**Comment by kapc3d** [comment]
будет в след релизе
