### ISSUE TITLE
Короткие надписи мотиваторов

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#45]
Надо еще сократить короткие надписи мотиваторов. Я сама сократила, они лежат в карточке фичи:

https://www.notion.so/5-3-2-6171413f02df4acc9d40f58eb926c48f

Поле описание, выделено жирным.

Точку в конце не надо ставить!

Тк не знаю это подставляется с бэка или где-то на фронт, отметила ВСЕХ

**Comment by hainamantik** [comment]
Тексты сократил, появятся со следующим обновлением (ближайший час)
