### ISSUE TITLE
Уведомление № 5 - Редирект в неверный раздел приложения

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#46]
(1)

@davidvirabian надо сократить текст ЭТОГО уведомления и всех остальных. До такого же размера как я сократила описания мотиваторов. Чтобы НИЧЕГО не уходило под троеточие, этого просто пользователь не увидит никогда. Давно прошу.

(2) 2 all редирект уведомления № 5 происходит не в раздел Настройки - Основные настройки, а в Календарь! получается ерунда.

**Comment by hainamantik** [comment]
(1) Дубликат https://github.com/avatar-project/public-issues/issues/47
(2) Актуально, мы шлём уведомление такой структуры:
```
{
   "title":"",
   "body":"",
   "notification_type":"view",
   "payload":{
      "author":"Аватар",
      "view_id":"settings",
      "meta":{}
   }
}
```
`view_id` конкретно указано, что надо открыть раздел настроек

**Comment by Monteguen** [comment]
> (1) Дубликат #47
> (2) Актуально, мы шлём уведомление такой структуры:
> 
> ```
> {
>    "title":"",
>    "body":"",
>    "notification_type":"view",
>    "payload":{
>       "author":"Аватар",
>       "view_id":"settings",
>       "meta":{}
>    }
> }
> ```
> 
> `view_id` конкретно указано, что надо открыть раздел настроек

неверное содержание поля view_id поэтому редиректит по дефолту в календарь. settings находится по адресу profile/settings
плюс в связи с тем что вы использовали view для group_assset вызываю дефолтный редирект в календарь, до тех пор пока вы для grup_asset не выделите отдельный тип

**Comment by danwhale** [comment]
> > (1) Дубликат #47
> > (2) Актуально, мы шлём уведомление такой структуры:
> > ```
> > {
> >    "title":"",
> >    "body":"",
> >    "notification_type":"view",
> >    "payload":{
> >       "author":"Аватар",
> >       "view_id":"settings",
> >       "meta":{}
> >    }
> > }
> > ```
> > 
> > 
> > `view_id` конкретно указано, что надо открыть раздел настроек
> 
> неверное содержание поля view_id поэтому редиректит по дефолту в календарь. settings находится по адресу profile/settings

> плюс в связи с тем что вы использовали view для group_assset вызываю дефолтный редирект в календарь, до тех пор пока вы для grup_asset не выделите отдельный тип

Честно не понимаю в чём там проблема взаимодействия с АПИ и чем вызвана необходимость `group_assset`  выделять в отдельный тип?  Есть раздел приложения, есть дополнительная мета, которая необходима для работы задуманной логики. Со стороны бэкэнда поддерживать новый тип уведомления нам очень накладно. Если пугает логика именования с `view` можем переименовать на что-то более абстрактное, включающее в себя и просмотр раздела и открытие раздела с нужной метой (в общем-то как и в календарь, мы отправляем на конкретную дату).

**Comment by Monteguen** [comment]
@danwhale потому что тип view предполагает что мы вызовем навигацию со строкой view_id. оно также предполагает автоматическую навигацию при клике на внешений пуш и клик по элементу ленты
функции "редирект" и "открытие ассет группы" это абсолютно разные механики. 
Если не хочешь плодить notification_type то уж лучше засунуть его в notification_type: asset, но у ассетов также совершенно другая механика, которая рендерит один элемент по полю payload, когда для group_asset нужно создавать массив элементов, как будто это элемент ленты asset_group .-.
Можно оценки и ассеты объединить в один тип пушей, потому что их механика одинаковая

**Comment by hainamantik** [comment]
> @danwhale потому что тип view предполагает что мы вызовем навигацию со строкой view_id. оно также предполагает автоматическую навигацию при клике на внешений пуш и клик по элементу ленты
> функции "редирект" и "открытие ассет группы" это абсолютно разные механики.
> Если не хочешь плодить notification_type то уж лучше засунуть его в notification_type: asset, но у ассетов также совершенно другая механика, которая рендерит один элемент по полю payload, когда для group_asset нужно создавать массив элементов, как будто это элемент ленты asset_group .-.
> Можно оценки и ассеты объединить в один тип пушей, потому что их механика одинаковая

Это механики фронтенда, а не бэка. Вы у себя можете делать какие угодно редиректы/попапы, мы вам просто передаём Enum из возможных типов действий, вся задача вам - определить тип действия по полученным от нас данным и сделать нужное.

Если у вас через месяц на нотификашку "посмотри статистику за сегодня" должен будет открываться попап со статистикой, а не просто окно уведомления, вы тоже скажете нам менять структуру? Это нелогично. А если бы у нас были несколько клиентов, например ещё веб приложение, нам бы под него тоже надо было подстраиваться с типами редиректов в уведомлениях?

**Comment by kapc3d** [comment]
> > @danwhale потому что тип view предполагает что мы вызовем навигацию со строкой view_id. оно также предполагает автоматическую навигацию при клике на внешений пуш и клик по элементу ленты
> > функции "редирект" и "открытие ассет группы" это абсолютно разные механики.
> > Если не хочешь плодить notification_type то уж лучше засунуть его в notification_type: asset, но у ассетов также совершенно другая механика, которая рендерит один элемент по полю payload, когда для group_asset нужно создавать массив элементов, как будто это элемент ленты asset_group .-.
> > Можно оценки и ассеты объединить в один тип пушей, потому что их механика одинаковая
> 
> Это механики фронтенда, а не бэка. Вы у себя можете делать какие угодно редиректы/попапы, мы вам просто передаём Enum из возможных типов действий, вся задача вам - определить тип действия по полученным от нас данным и сделать нужное.
> 
> Если у вас через месяц на нотификашку "посмотри статистику за сегодня" должен будет открываться попап со статистикой, а не просто окно уведомления, вы тоже скажете нам менять структуру? Это нелогично. А если бы у нас были несколько клиентов, например ещё веб приложение, нам бы под него тоже надо было подстраиваться с типами редиректов в уведомлениях?

коллеги, давайте не будем играться в "ты дурак, сам дурак", и делать так чтобы было удобно обеим сторонам, а не исходить из позиции "нам так удобно, а вы ##итесь с этим как хотите"

потому по конструктиву: структура апи должна отвечать общим механикам фронт+бэк, потому давайте многовложенную структуру типов и действий структурируем. Если это **редирект** в какой то раздел приложения (календарь, настройки да что бы то ни было) это один тип, если этооткрытие какого то контента (опрос, статья, подборка оценка блаблабла) это открытие контента и другой тип взаимодействия. **Редиректа в подборку/мотиватор не существует, открытия настроек и календаря тоже не существует.**

Исходя из этого я вижу такую структуру, что тип уведомления view - это редирект, тип уведомления asset - это открытие ассета, так вот открыть подборку должно класться в asset, редирект в календарь или настройки - в view

@danwhale @hainamantik 

@Monteguen создайте понятную enum типизацию для разделов приложения (согласно твоей карте, если вы этого еще не сделали), чтобы в апи view прилетало всегда понятное тебе значение раздела приложения

**Comment by kapc3d** [comment]
@davidvirabian проверяли?

**Comment by kbochenina** [comment]
Уведомление № 5 (в части Редирект на настройки) работает верно

v. 1.0.3 rc

По другим аспектам работы уведомлений будут открываться новые тикеты.
