### ISSUE TITLE
Название и описания уведомлений

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#47]
Я посмотрела еще раз на таблицу https://www.notion.so/6974413354e54b94a9ff13d5ee50147f с уведомлениями

Сейчас не нравится 2 вещи:

(1) длинные тексты в колонке Текст. Они не помещаются на мотиватор (убираются под троеточие) и не доступны никогда.

(2) Смысловой разнобой в колонке Заголовок. Иногда как будто Аватар обращается (Разметь событие, Возьми меня с собой на пары), иногда это информационное сообщение (Через 60 минут начало мероприятия), в случае "Интеллект Аватара" указан видимо источник сообщения.

Поэтому 2 конкурирующих предложения:

I ) 
Поле Заголовок отдать под источник уведомления (Аватар, Команда Аватара, Декан ФЦТ и т.д.)
А в Описание использовать текущий Заголовок (кроме последнего уведомления, там это сокращенная колонка Текст)

II) Убрать смысловой разнобой, оставив единую семантику обращений (например, все время обращается Аватар) и _существенно_ сократить тексты в колонке Текст, чтобы умещалось все до троеточия.

Высказываемся.

**Comment by davidvirabian** [comment]
Хорошее замечание.
Вариант №1 видится мне гораздо более логичным и интересным.
Вариант №2 тоже рабочий, но у нас получится подряд несколько уведомлений с заголовком "Аватар,Аватар,Аватар..."

**Comment by davidvirabian** [comment]
Поправил все текста с лимитом в 60 символов. Теперь все текста должны помещаться на плашке уведомлений.

**Comment by hainamantik** [comment]
Есть предложение здесь же: для [уведомления](https://www.notion.so/a30dc673854748069cde950fd271d039) поменять заголовок с "Ты вчера оценил новость в подборке {ИмяПодборки}. Давай разметим ее?" на "Ты вчера оценил событие {ЗаголовокСобытия}. Давай разметим его?"
1.) Оценивать мы можем только события
2.) Имя подборки не несёт никакой информации о том, про какой ассет мы говорим
3.) Отслеживать, из какой подборки оценивал пользователь событие, проблематично

@davidvirabian  @kbochenina

**Comment by kbochenina** [comment]
@hainamantik Я поддержу

**Comment by kbochenina** [comment]
@davidvirabian если вариант № 1 ближе, то модифицируй таблицу в соответствии с № 1 и предложением @hainamantik , повесь сюда ссылку. Тексты уведомлений мы модифицируем на бэке, так?

**Comment by hainamantik** [comment]
> Тексты уведомлений мы модифицируем на бэке, так?

Да

**Comment by davidvirabian** [comment]
Контекстуально проще вариант 2 использовать. Т.е. в заголовке указывать "Аватар" / "Команда Аватара. Поэтому, так и оставил.
@hainamantik  возьмете в работу?

> Я посмотрела еще раз на таблицу https://www.notion.so/6974413354e54b94a9ff13d5ee50147f с уведомлениями
> 
> Сейчас не нравится 2 вещи:
> 
> (1) длинные тексты в колонке Текст. Они не помещаются на мотиватор (убираются под троеточие) и не доступны никогда.
> 
> (2) Смысловой разнобой в колонке Заголовок. Иногда как будто Аватар обращается (Разметь событие, Возьми меня с собой на пары), иногда это информационное сообщение (Через 60 минут начало мероприятия), в случае "Интеллект Аватара" указан видимо источник сообщения.
> 
> Поэтому 2 конкурирующих предложения:
> 
> I )
> Поле Заголовок отдать под источник уведомления (Аватар, Команда Аватара, Декан ФЦТ и т.д.)
> А в Описание использовать текущий Заголовок (кроме последнего уведомления, там это сокращенная колонка Текст)
> 
> II) Убрать смысловой разнобой, оставив единую семантику обращений (например, все время обращается Аватар) и _существенно_ сократить тексты в колонке Текст, чтобы умещалось все до троеточия.
> 
> Высказываемся.

**Comment by hainamantik** [comment]
> Контекстуально проще вариант 2 использовать. Т.е. в заголовке указывать "Аватар" / "Команда Аватара. Поэтому, так и оставил.
> @hainamantik возьмете в работу?
> 
> > Я посмотрела еще раз на таблицу https://www.notion.so/6974413354e54b94a9ff13d5ee50147f с уведомлениями
> > Сейчас не нравится 2 вещи:
> > (1) длинные тексты в колонке Текст. Они не помещаются на мотиватор (убираются под троеточие) и не доступны никогда.
> > (2) Смысловой разнобой в колонке Заголовок. Иногда как будто Аватар обращается (Разметь событие, Возьми меня с собой на пары), иногда это информационное сообщение (Через 60 минут начало мероприятия), в случае "Интеллект Аватара" указан видимо источник сообщения.
> > Поэтому 2 конкурирующих предложения:
> > I )
> > Поле Заголовок отдать под источник уведомления (Аватар, Команда Аватара, Декан ФЦТ и т.д.)
> > А в Описание использовать текущий Заголовок (кроме последнего уведомления, там это сокращенная колонка Текст)
> > II) Убрать смысловой разнобой, оставив единую семантику обращений (например, все время обращается Аватар) и _существенно_ сократить тексты в колонке Текст, чтобы умещалось все до троеточия.
> > Высказываемся.

Посмотри сейчас в приложении на названия мотиваторов, там уже всё вроде обновлено

**Comment by hainamantik** [comment]
Если всё сходится то можно даже закрыть

**Comment by davidvirabian** [comment]
Там нет уведомлений за сегодняшний день. В общем, на бэке вы поправили все, да?

**Comment by danwhale** [comment]
да

**Comment by hainamantik** [comment]
> Там нет уведомлений за сегодняшний день. В общем, на бэке вы поправили все, да?

я тебе отправил все тестовые уведомления, должны были точно прийти

**Comment by davidvirabian** [comment]
Вижу, все Окей
Спасибо
