### ISSUE TITLE
Создание новой подборки - Обязательное добавление описания

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#48]
При создании подборки обязательно надо добавлять описание.

Я вследствие этого всегда просто заполняю его какими-то случайными символами, и меня это раздражает.

Предложение: смягчить требование на обязательность этого поля (но тогда надо убирать подсветку Описание меньше 10 символов) тоже

**Comment by davidvirabian** [comment]
Согласен. Тоже ощутил эту боль. Я бы вообще сделал описание необязательным.

**Comment by kapc3d** [comment]
@danwhale со стороны бэка есть проверка на валидность по количеству символов в описании?

**Comment by danwhale** [comment]
> @danwhale со стороны бэка есть проверка на валидность по количеству символов в описании?

есть) Давайте уберём @hainamantik

**Comment by hainamantik** [comment]
Я уберу, но обращаю внимание, что подборка классифицировалась по целям исходя из текстов описания, поэтому теперь в подборках не будет целей и мы не сможем строить вокруг них логику добавления новых выдач. Только по тегам, источникам, типам ассетов.

**Comment by danwhale** [comment]
> Я уберу, но обращаю внимание, что подборка классифицировалась по целям исходя из текстов описания, поэтому теперь в подборках не будет целей и мы не сможем строить вокруг них логику добавления новых выдач. Только по тегам, источникам, типам ассетов.

Да, цели только наши, подкапотные.

**Comment by davidvirabian** [comment]
В итоге, убираем необходимость заносить описание в созданной подборке?

**Comment by danwhale** [comment]
да.

**Comment by hainamantik** [comment]
Со своей стороны уберём лимит к вечеру, @kapc3d вы тоже уберите лимит на длину описания

**Comment by kapc3d** [comment]
взяли в работу

**Comment by kapc3d** [comment]
в следующем билде
