### ISSUE TITLE
Создание новой подборки - реакция на нажатие кнопки Готово

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#50]
По созданию новой подборки по нажатию кнопки Готово закрывать автоматически это окно и чтоб показывались Мои дела. А то сейчас надо делать доп действие, нажимать кнопку Назад

**Comment by davidvirabian** [comment]
У меня при создании подборки и нажатии кнопки "готово" сразу происходит редирект в "мои дела"

**Comment by kapc3d** [comment]
в текущем билде у всех все отрабатывает нормально
@kbochenina нужно описание как воспроизвести баг, тогда откроем тикет, пока закрываю
