### ISSUE TITLE
Уведомление № 8 - редирект на Календарь вместо подборки по целям [dev]

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#53]
Смотрела в версии dev

Уведомление № 8 о прогрессе по целям - как ты себя чувствуешь к середине недели - редиректит на Календарь, никакого смысла (видимо недоделано)

**Comment by kapc3d** [comment]
еще не реализован механизм редиректа на ассет-группу с обеих сторон

**Comment by danwhale** [comment]
С нашей стороны готово давно, идут перебранки по спецификации API.

**Comment by kapc3d** [comment]
починено, ожидает проверки в следующем билде

**Comment by davidvirabian** [comment]
Происходит редирект в подборку. Все норм.
