### ISSUE TITLE
Подтверждение удаления уведомления - надо ли?

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#54]
Предложение убрать подтверждение Удалить уведомление? при нажатии на мусорку для уведомления. Уведомление - вещь краткосрочная, давайте удалять и всё. По подборкам я бы оставила, потому что пользователь тратит время на их создание.

**Comment by davidvirabian** [comment]
Соглашусь, лучше сделать эту micro job как можно проще, тк постоянное подтверждение удаления может сильно раздражать.
<По подборкам я бы оставила, потому что пользователь тратит время на их создание.> - тоже соглашусь. Когда создавал подборки для юзеров, случайно удалил пару созданных. Пришлось создавать заново
