### ISSUE TITLE
Пользовательская подборка - не сохраняются выбранные поля [dev]

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#55]
Когда создал подборку вручную и потом заходишь чтобы ее редактировать, показываются отмеченными ранее выбранные тэги, сохранено описание и название, но НЕ сохранен выбор:

- типа выдач
- полагаю что источников тоже

**Comment by danwhale** [comment]
@hainamantik с нашей стороне не отдаём, судя по спеке: 

![image](https://user-images.githubusercontent.com/23121997/108323312-8fd5e880-71d7-11eb-9765-59333d50c645.png)

**Comment by hainamantik** [comment]
![image](https://user-images.githubusercontent.com/65557222/108324307-c6f8c980-71d8-11eb-9b1f-8bd291188298.png)
https://redocly.github.io/redoc/?url=https://test.avatar.onti.actcognitive.org/feed/api.json#operation/get_asset_group_handler_groups__group__get

Запрос на test стенд сейчас:
```
Asset group info: 
{'asset_types': ['events', 'articles'],
 'description': 'Побить олимпийский рекорд или просто научиться играть в '
                'шахматы? Здесь ты найдёшь спорт по душе',
 'goals': [],
 'image': '',
 'origins': [],
 'tags': ['спорт',
          'барсы',
          'настольныйтеннис',
          'гребля',
          'бадминтон',
          'баскетбол',
          'футбол',
          'бокс',
          'скалолазание'],
 'title': 'Спорт',
 'top_goals': [5],
 'uid': '9d998ec4-2646-422e-9437-39dfbef809dd'}
```
Проблема не в бэке, снимаю с себя

**Comment by hainamantik** [comment]
> @hainamantik с нашей стороне не отдаём, судя по спеке:
> ![image](https://user-images.githubusercontent.com/23121997/108323312-8fd5e880-71d7-11eb-9765-59333d50c645.png)

Надо актуализировать примеры для апи, создам таску в наших тикетах(

**Comment by danwhale** [comment]
@kapc3d берите в работу)

**Comment by kbochenina** [comment]
Тип контента - сохраняется, а источники в другом тикете мы решили деактивировать. Закрываю
