### ISSUE TITLE
Визуальная дифференциация мотиваторов - иконки целей

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#56]
Высказывалась идея, и даже вроде согласовали - что хорошо бы чтобы на мотиваторах, под которыми лежат подборки _по целям_, были иконки целей. Но также согласовали что это в улучшение.

**Comment by davidvirabian** [comment]
Да. Такая идея была согласована. Но у нас там было слишком неконструктивное обсуждение, к сожалению. Поэтому, четкой фиксации не было.

В новом билде я видел дифференциацию мотиваторов – были разные иконки. Честно, было не совсем информативно. 
Ассоциативный ряд тоже прорабатывать надо. Но дифференциация была, что уже хорошо

**Comment by kapc3d** [comment]
насколько известно от @danwhale к нам не летает мета по соответствию мотиватора цели, как будем получать эту инфу сможем подставлять иконки

**Comment by hainamantik** [comment]
Если всё согласовали - добавим поле к выдачам общей ленты с соответствием мотиватора целям.
Надо тогда где-то зафиксировать и закрывать этот тикет как решённый.

**Comment by davidvirabian** [comment]
В таком случае, фиксирую [здесь](https://www.notion.so/1c901d06acf34a888673701c0694b31d) и закрываю.
