### ISSUE TITLE
Уведомление № 8 с переходом на подборки целей - прояснение

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#57]
касательно вот этого типа уведомлений вопрос
https://www.notion.so/9234da9f81924035a744d9c5c6c9b2e5
У нас сейчас имеется 8 предзаданных мотиваторов, каждый из которых соответствует своей топ цели (спорт, наука и т.п.).
Также есть ещё 2 мотиватора "общего" плана (новости итмо и essential).
Пользователям после онбординга назначаются мотиваторы, соответствующие трём топ целям (три штуки) и 2 рандомных из общего списка (пока что всегда это "новости итмо" и "essential").

В описании уведомления сказано, что каждый день предлагается редирект в подборку, соответствующей одной из топ целей пользователя.

Вопрос такой: мы просто предлагаем прочитать подборки, которые УЖЕ имеются у него в ленте (посколько добавлены туда по умолчанию из-за целей), или мы должно предлагать ему читать какие-то НОВЫЕ подборки (списка которых нет)? Так же непонятен тогда механизм чтения "чужой" подборки, если ты не можешь добавить её к себе

**Comment by kbochenina** [comment]
Отвечу как вижу:

(1) имелись в виду те подборки которые УЖЕ имеются. Смысл в том чтобы привлечь внимание к подборке, как бы подтолкнуть что-то посмотреть по цели.

Наверное лучше было бы оставить вообще ТОЛЬКО пуш по уведомлению № 8, а в Мои дела не слать (тк сейчас и пуш, и плашка в Моих делах). Тогда логика простая - аватар тебе присылает пуш, если ты откликаешься - переходишь к контенту сразу. Но я не знаю у вас насколько связаны пуши и уведомления в Моих делах.

Если нельзя оставить только пуш - давай указывать на уже имеющуюся подборку.. ничего страшного

(2) Про механизм чтения чужой подборки тогда наверное вопрос снят (тк если "чужая" = НОВАЯ) в терминологии Саши, то их нет.

(3) По хорошему если делать № 1, то я б туда просто накидывала рандомные выдачи по цели, НЕ вошедшие в его стандартную подборку (тк у нас max 10 доступно). Но это конечно уже новая логика.

Поэтому мое предложение - в (1) сформулировано.

**Comment by davidvirabian** [comment]
Как должно быть:
1. Пользователь всегда имеет подборку "Essential" и  " Новости ИТМО" – эти подборки имеют строго определенные источники.
2. Пользователь имеет 3 подборки по топ-целям, которые формируются без тегов (по иконкам, как в ленте Аватара)
3. Каждый день пользователь получает push-уведомление, с подборкой по одной из топ-целей. Каждая подборка (на каждый день недели, с пн-пт) имеет предзаданные теги.
Благодаря такому "комбо" получится показать интеллектуальность приложения и разнообразить взаимодействие с экраном "Моих дел".

При этом, соглашусь, что пуш должен вести сразу в подборку, иначе экран "мои дела" будет перегружен

**Comment by hainamantik** [comment]
> Каждая подборка (на каждый день недели, с пн-пт) имеет предзаданные теги.

Можно расшифровать это, что за теги? У нас сейчас есть 10 подборок (8 по топ целям, 2 обших), у всех них есть теги и множество других характеристик для фильтрации контента (те, что ты указывал при создании подборок, я потом из базы перенёс это)

Рассмотрим пример:
Пришёл новый юзер, задал себе цели наука, коммуникации, досуг. У него в ленте появились подборки "Наука", "Коммуникации", "Досуг", "Новости ИТМО", "Essential".

Каждый день ему должна приходить случайная подборка из ("Наука", "Коммуникации", "Досуг"), которые и так есть в ленте, верно?

**Comment by hainamantik** [comment]
Мне вот сейчас прояснили, что вроде как у нас должно быть 8 + 8 + 2 = 18 подборок
8 только с топ целями и без тегов, названия для них есть в тз. Эти подборки висят в лентах пользователей и контент в них попадает только на основании целей (следовательно контента много, и он не всегда подходящий)

8 с топ целями и тегами и такие подборки можно увидеть только через прочтение уведомления, которое приходит каждый день. Для этих подборок не прописаны тексты в ТЗ, но у них есть теги. Контент в них попадает по... тегам? То есть это ультимативные подборки с крутым контентом, но ты их видишь только один раз в день при открытии уведомления.

2 подборки общие и всегда висят в ленте.

Как всё-таки должно быть?

**Comment by kbochenina** [comment]
@hainamantik мы тут еще с коллегами подискутировали в #64 , и твое последнее сообщение соответствует истине. 

@danwhale @davidvirabian по реализации уже тогда сами уточняйтесь

**Comment by hainamantik** [comment]
Понял, спасибо за пояснения. В ближайшее время будет работать по [этой](https://github.com/avatar-project/public-issues/issues/57#issuecomment-781114084) механике
