### ISSUE TITLE
Типы событий и начисляемые баллы - разместить в Notion

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#58]
типы событий и начисляемые баллы за них в ноушене так и не появились @hainamantik

**Comment by kbochenina** [comment]
@davidvirabian добавить или уточнить ГДЕ лежит. И расшарить информацию в канале board updates и в чате board

**Comment by davidvirabian** [comment]
https://www.notion.so/22-b9a1132ea2244793a60d7f149db09f82?v=b67e23ad24684e4f9e551ee1f1bd9f90

Скидывал @hainamantik, вопрос тоже под контролем.
Пришлю в board

**Comment by hainamantik** [comment]
https://www.notion.so/ff2f6645f8924533a2223ecd6be454be?v=2dab05161c4f4c84b4843e4d093bc9f3 если точнее

**Comment by davidvirabian** [comment]
> https://www.notion.so/ff2f6645f8924533a2223ecd6be454be?v=2dab05161c4f4c84b4843e4d093bc9f3 если точнее
> 
> 

Да, спасибо 
В борде та же ссылка)
