### ISSUE TITLE
Механизм обновления подборок - подгрузка контента и ограничения по числу выдач подборки

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#59]
Что надо прояснить:

1. Max ограничение по числу выдач в подборке (обозначу MAX). Оно же число серых полосочек внизу подборки.
2. Наличие возможности и механизм подгрузки дополнительных выдач в рамках ОДНОЙ подборки (когда пользователь просмотрел MAX выдач, в подборке еще остались выдачи, и он хочет просмотреть еще в рамках этой же подборки).

В ТЗ так:
>Выдач всегда внутри мотиватора не больше 5.
>Если пользователь просмотрел все 5 выдач подборки, в этом случае подгружаются еще 5

Варианта вижу 2:

(1) Увеличить MAX (вроде по факту в приложении сейчас так), по кр. мере MAX = 10 сейчас наблюдаю. И не делать подгрузку контента.
+ уже есть
- резко ограничено число доступного контента
- возникает довольно нелепая ситуация с индикаторами непрочитанных постов, а именно показывается в индикаторе овермного, посмотреть ты можешь MAX, а остальное не можешь никогда (возможно что-то оттуда подгрузится по условию: >Обновление происходит по факту поступления нового контента, но это лишь малая часть)

Если идти путем № 1- надо что-то делать с индикаторами постов (на них заведу отдельный тикет).

(2) Реализовать механизм подгрузки + MAX постов после завершения просмотра всей подборки. Обсуждалось, и вроде бэк готов, но вопрос возник как делать с фронт стороны (свайп вниз @kapc3d сказал что плохо)

В качестве идеи. Может быть после завершения подборки (MAX постов) показывать специальную выдачу с 2 кнопками - Смотреть дальше, К другой подборке? Смотреть дальше - + MAX постов, К другой подборке - то что сейчас происходит по нажатию на последнюю выдачу пред. подборки.

№ 2 с моей стороны лучше, но более трудоемко видимо.

**Comment by davidvirabian** [comment]
Пока читал комментарий, тоже пришел к мысли, что можно предлагать юзеру подгрузить контент, показав выдачу с двумя кнопками.
Исходя из моего понимания разработки, №2 вариант сделать совсем не проблематично. Просто мы этом особо не фокусировались.

**Comment by kapc3d** [comment]
с точки зрения пользователя варинт №2 мне нравится больше.
как реализацию я вижу:
1. вместе с ассетами в конце каждой подборки (при наличии доступного контента) бэк присылает новый тип ассета (хз как назвать, например "update_assetgroup") для которой мы сделаем верстку как вы сказали, а внутри ассета будет лежать какая то ссылка или пояснение на запрос по которому мы подгрузим доп выдачи.
2. вместе с подборкой сообщать сколько будет загружено + "сколько осталось"/"всего доступно" контента и дальше мы уже как то на своей стороне будем это разруливать...

в общем механизм надо адекватно спроектировать чтобы на каждой стороне (фронт/бэк) делалась своя работа, без перекладываний

насчет прогнозной времени реализации на стороне фронта затрудняюсь пока сказать, вероятность запилить до старта ЗБТ есть, но пока что мала.

**Comment by hainamantik** [comment]
к комменту выше:
п.1 это дикий костыль и так делать точно не будем
п.2 в [спеках](https://redocly.github.io/redoc/?url=https://test.avatar.onti.actcognitive.org/feed/api.json#operation/get_content_of_asset_group_handler_groups__group_uid__feed_get) указано, что вы можете отсылать в запросе номер страницы. Сейчас по умолчанию на странице 10 ассетов, вы можете сколько угодно запрашивать следующие страницы после завершения прочтения предыдущих.  Если в ответ пришёл пустой массив, значит ассеты кончились.

**Comment by kbochenina** [comment]
@hainamantik Саша, а п. 1 - это не так как сейчас сделано? Или я не поняла как после просмотра MAX выдач еще что-то увидеть из подборки, пока она сама когда-то там не обносится

**Comment by hainamantik** [comment]
> @hainamantik Саша, а п. 1 - это не так как сейчас сделано?

Про пункт 1, это я про то, что мы не будет выдумывать отдельный тип выдачи просто для того, чтобы фронты в конце списка отрисовывали особенный элемент, который нужен исключительно в логике работы фронтенда для подгрузки следующих элементов.

> Или я не поняла как после просмотра MAX выдач еще что-то увидеть из подборки, пока она сама когда-то там не обновится

Механика на бэкенде есть, нужно просто послать ещё один запрос, и получишь следующие элементы подборки. Фронтенд её не использует.

**Comment by kbochenina** [comment]
@kapc3d призываю тебя, чтобы ты сказал - можно ли реализовать для релиза № 2 с учетом того что бэк написал выше. Или же сейчас вы не успеете и мы идем по варианту № 1 из титульного поста.

+ ответь в теме #60  , тк если мы НЕ меняем текущую логику и НЕ делаем догрузку контента, то надо менять индикаторы на мотиваторах. Предложения от нас в #60

**Comment by kbochenina** [comment]
Копирую сюда аргументы Андрея чтоб не скакать между тредами:

[1] Если мы избавляемся от счетчика непрочитанного жизнь упрощается, но что делать нам?
Пользователю пришла подборка на 5 постов, пользователь долистал до конца
Мы показываем экран "У тебя есть еще контент в подборке. Загрузить еще?"
Пользоавтель нажимает Да

        Мы добавляем ему к его 5 еще 5 новых? то есть у него подборка становится на 10 постов? потом еще добавляет 5, потом еще 5 и так до 150....
        он выходит из подборки - что после этого он увидит при повторном входе в нее? @hainamantik пришлет нам только непрочитанные посты? или пришлет указание на страницу на которой пользователь остановился читать? или пользователь пойдет листать с самого начала каждый раз добавляя по 5 постов, потом выйдет и опять по новой?

        мы удаляем просмотренные пять и он как будто снова смотри новые 5 постов в той же подборке, т.е. пользователь не может откатиться назад, хотя вроде заявлялось определенное время жизни ассета в ленте. когда пользователь выйдет из подборки что будет там при повторном входе? новый контент?

Пользователь нажимает Нет и переходит на следующую подборку

    Что пользователь увидит при повторном входе в подборку?

[2] объясню механику как я предполагал когда выдвигал идею про сторис:
у пользователя всегда доступен в подборке (набор плашек внизу) весь актуальный по подборке контент, и у него есть время жизни (3 дня например или протухание, например прошедшее событие), пользователь открывает подборку видит сразу по строке навигации объем предлагаемого контента и где он в ней. и смотреть контент начинает с того места где закончил
введение пагинации и ограничений вроде "не больше 5 выдач" убивает эту идею, ибо пользователь не понимает сколько у него контента предоставлено и сколько еще может посмотреть и где он в общем потоке по данной теме
пагинация на загрузку саммих ассетов мне понятна, но пагинация глобальная на всю подборку имхо усложнение и путаница

**Comment by kbochenina** [comment]
Сложилось ощущение, что догрузка добавляет слой логики, по которой нет ясности (то что написано про повторные входы в подборку и тд).

Поэтому предложение:
(1) на релиз оставить без подгрузки, но увеличить MAX (25? 50? не ставить ограничений?) просто чтобы в подборке было больше контента. 

Если можно НЕ ставить ограничения MAХ, то это наилучший вариант тк пользователю доступен весь контент подборки.

Если я правильно понимаю, повторно заходя сейчас в подборку, мы все время начинаем с начала, и подборка обновляется в том случае, если поступил какой-то контент. Тогда механика работы, что у него есть довольно статичная подборка, по которой он идет и если что-то хочет запомнить, запихивает это в избранное. А повторный просмотр подборки ему интересен, только если в нее загрузилось что-то новое. 

(2) По индикаторам сделать без чисел:
Например:
    есть непросмотренные (круг с заливкой)
    все просмотрены, подборка не пустая (без круга)
    подборка пустая (какой-то предупреждающий знак)

(3) Версию с подгрузкой запланировать как enhancement, то есть воспринимать эту версию как временное решение.
 
@kapc3d @danwhale @hainamantik

**Comment by kbochenina** [comment]
Итого сошлись на последнем посте с MAX = 25 и "бесчисельным" индикатором мотиваторов с 3 состояниями.

**Comment by kbochenina** [comment]
MAX = 25 работает.. а индикаторы это другой тикет. Закрываю и меняю метку на enhancement. Тут есть еще чего обсуждать
