### ISSUE TITLE
qr код не обновляется [dev]

### ISSUE THREAD

**Issue by davidvirabian** [avatar-project/public-issues#66]
При смахивании страницы вниз, qr код не обновляется

**Comment by kapc3d** [comment]
@danwhale пожалуйста, дай пояснение механики обновления QR кода. если я правильно помню - у него есть время жизни. и если на сервере QR не поменялся, то и у нас он не обновится. Сколько сейчас таймаут жизни QR кода, чтобы даже мы сами могли это оттестировать?

**Comment by hainamantik** [comment]
QR код одноразовый: каждый раз, когда вы его запрашиваете, мы перенаправляем запрос в ИТМО, других способов взаимодействия с их апи пока нет.
Когда человек использует QR код для прохода куда-нибудь, его содерижимое меняется. Но об этом можно будет узнать только попробовав обновить QR.
Также код обновляется раз в 24 часа, если не был использован.

**Comment by shpaker** [comment]
Короч, я уж писал в аватар борд, но это кануло в бездну:

- [ ] QR коду нужна явная кнопка ручного обновления без неочевидных механик 
- [ ] Необходимо чтоб фронт не ограничивалися одним запросом в случае проваленного запроса, а делал несколько попыток с увеличивающейся паузой (но думаю не более трех и чтоб общее время не было больше 10 секунд)
- [ ] я бы подписал где-нибудь, что это пропуск в здание, а то как-то даж и не ясно что это за хрень и почему она у нас на главной

**Comment by kapc3d** [comment]
> QR код одноразовый: каждый раз, когда вы его запрашиваете, мы перенаправляем запрос в ИТМО, других способов взаимодействия с их апи пока нет.
> Когда человек использует QR код для прохода куда-нибудь, его содерижимое меняется. Но об этом можно будет узнать только попробовав обновить QR.
> Также код обновляется раз в 24 часа, если не был использован.

вот поэтому я спрашивал какова механика. 
т.е. я правильно понимаю, что явно увидеть обновление qr кода при запросе с сервера ИТМО мы сможем в 2х случаях:
- использовав его для входа
- подождав пока пройдет 24 часа
верно?

таким образом:
если будет кнопка принудительного обновления кода, и пользователь будет по ней жамкать - он не увидит изменений без выполнения одного из пунктов выше => обманутые ожидания => потому с кнопкой надо делать так:

> вы проксируете у себя этот запрос и делаете обработчик, который при нажатии кнопки будет давать нам сообщения вроде "код не изменился, вот вам новый код, сервре не отвечает, вас забанили и т.д." чтобы мы могли сказать пользователю, что же там происходит с его кодом.

про подпись подумаем, но я скорее склоняюсь к тому чтобы просто сказать об этом в онбординге и всё

насчет механизма обновления с множественными запросами - возьмем в работу

**Comment by danwhale** [comment]
>т.е. я правильно понимаю, что явно увидеть обновление qr кода при запросе с сервера ИТМО мы сможем в 2х случаях:

> - использовав его для входа
> - подождав пока пройдет 24 часа
> верно?

Механика там убогая:
1) мы не можем проверить использовался ли для входа\выхода QR код
2) то что он протухает через 24 часа -- вероятно факт, но проверить его валидность мы не можем никак... 

Я вижу так, что нужно постоянно его рефрешить, то есть иметь всегда самый свежий QR, ответ с тем, что сервер не отвечает мы будем обрабатывать да.

**Comment by davidvirabian** [comment]
А с какой периодичностью qr будет обновляться? Не слишком это нагрузит бэк?
Может, имеет смысл добавить иконку "обновить"?

**Comment by danwhale** [comment]
Автоматически мы обновлять его не можем, мы даём механизм, нагрузки частые (в разумных пределах, без доса) обновления не вызовут

**Comment by kapc3d** [comment]
> > т.е. я правильно понимаю, что явно увидеть обновление qr кода при запросе с сервера ИТМО мы сможем в 2х случаях:
> 
> > * использовав его для входа
> > * подождав пока пройдет 24 часа
> >   верно?
> 
> Механика там убогая:
> 
> 1. мы не можем проверить использовался ли для входа\выхода QR код
> 2. то что он протухает через 24 часа -- вероятно факт, но проверить его валидность мы не можем никак...
> 
> Я вижу так, что нужно постоянно его рефрешить, то есть иметь всегда самый свежий QR, ответ с тем, что сервер не отвечает мы будем обрабатывать да.

насколько мне известен механизм текущий - обновление QR кода происходит при каждом запросе на обновление страницы профиля, то есть если вдруг он обновится, то пользователь это увидит, сейчас еще раз уточню у @avatar-project/frontend-team

**Comment by Papakkkarlo** [comment]
Но он же не обновляется при каждом запросе, поэтому и код не меняется.

**Comment by kapc3d** [comment]
связано с #72

**Comment by kapc3d** [comment]
имхо закрываю и все остальное по qr кодам обсуждаем в #72
