### ISSUE TITLE
Работает не корректно – переключение между "Все"/"Расписание"/"Мои события"/"Подборки" [NEW] 

### ISSUE THREAD

**Issue by davidvirabian** [avatar-project/public-issues#67]
1. Мои события – работают исправно. Вижу только добавленные события.
2. В подборках ничего не отображается
3. Расписание не отображается
4. Расписание видно только во вкладке "Все"

**Comment by kapc3d** [comment]
у нас нет типов со стороны бэка. если работает фильтрация на уровне сессии (когда только добавил) значит на нашей стороне фильтрация отрабатывает.
ждем решение на стороне бэка

**Comment by danwhale** [comment]
Дубликат https://github.com/avatar-project/public-issues/issues/68 прикрою
