### ISSUE TITLE
Технические термины в текстах приложения

### ISSUE THREAD

**Issue by shpaker** [avatar-project/public-issues#69]
По глазам бьет злоупотребление тех терминов, например, слова разметить. Кажется, что для пользователя это слово несет минимум нагрузки и его лучше заменить на что-то более подходящее. Например, "оценить" либо что-то в таком духе.

**Comment by kbochenina** [comment]
@davidvirabian твоё

**Comment by davidvirabian** [comment]
Взял под контроль. 
Исправил в текущих текстах

**Comment by kbochenina** [comment]
Будем считать, что исправлено
