### ISSUE TITLE
Проблемы с вёрсткой на экране оценки события

### ISSUE THREAD

**Issue by davidvirabian** [avatar-project/public-issues#71]
![image](https://user-images.githubusercontent.com/70694105/108368513-98e0ad00-720b-11eb-9427-380aa4fb5887.png)
![image](https://user-image1s.githubusercontent.com/70694105/108368529-9da56100-720b-11eb-956c-bc4072dd13ea.png)
1. проблема - скролл съехал
2. У меня не получается попасть на зелёный кружок для проставления оценки. При нажатии на него у меня идет возврат на предыдущий экран.

**Comment by danwhale** [comment]
Для протокола: там 11й айфон.

**Comment by davidvirabian** [comment]
Да, спасибо.
Забыл упомянуть

**Comment by kbochenina** [comment]
@davidvirabian проблема сохраняется?

**Comment by davidvirabian** [comment]
Да, проверял около часа назад

**Comment by kapc3d** [comment]
будет в следующем билде

**Comment by davidvirabian** [comment]
Все супер
