### ISSUE TITLE
Тексты для пустых подборок

### ISSUE THREAD

**Issue by kbochenina** [avatar-project/public-issues#78]
Должны быть разные тексты для разных типов подборок:

Для пользовательских:

Пока в базе знаний Аватара нет информации по твоему запросу. Но если ты не будешь удалять подборку, Аватар даст знать, если что-то появится. А еще можно добавить в эту подборку больше тегов - может, что-то и найдется.

Для рекомендаций:

Пока Аватар ничего не нашел. Возможно, стоит добавить теги в профиле и установить цели?

Для встроенных подборок:
Пока Аватар ничего не нашел. Проверю данные и вернусь!

**Comment by kapc3d** [comment]
Забираем тексты в работу

**Comment by kapc3d** [comment]
фикс будет с версией 1.0.3
