### ISSUE TITLE
[front] Разделитель при выборе тегов

### ISSUE THREAD

**Issue by hainamantik** [avatar-project/public-issues#82]
**Describe the bug**

Между предложенными тегами и общим списком тегов (я так предполагаю) висит border-разделитель

**Steps To Reproduce**

1. Зайти в редактирование/создание подборки
2. Указать заголовок

**Expected behavior**

Убрать разделитель

**Screenshots**

![image](https://user-images.githubusercontent.com/65557222/108596547-d02f9500-7396-11eb-96d9-d3e04f3c4fe5.png)

**Environment (please complete the following information):**
 
 - Device: zte nubia z17
 - OS: android
 - Version: 1.0.0

**Comment by kbochenina** [comment]
v. 1.0.3 rc не наблюдается
