### ISSUE TITLE
[front] Возможность добавлять дубликаты тегов в своих подборках

### ISSUE THREAD

**Issue by hainamantik** [avatar-project/public-issues#83]
**Describe the bug**

При редактирвоании подборки можно добавлять любой тег сколько угодно раз

**Steps To Reproduce**

1. Перейти к редактированию подборки
2. Начать добавлять теги

**Expected behavior**

Список предложенных тегов должен исключать уже добавленные теги

**Screenshots**

![image](https://user-images.githubusercontent.com/65557222/108596586-08cf6e80-7397-11eb-8d08-82ae7380799a.png)

**Environment (please complete the following information):**
 
 - Device: zte nubia z17
 - OS: android
 - Version: 1.0.0

**Comment by kbochenina** [comment]
v. 1.0.3 - rc - проверено
